### ISSUE TITLE
Support for foldable callouts

### ISSUE THREAD

**Issue by eikowagenknecht** [rk-terence/gz-remark-callout#5]
Is support for foldable callouts still planned, as mentioned in the readme?

**Comment by rk-terence** [comment]
Hi. Supporting foldable callouts was initially intended, but later I discoverered that this is difficult without the aid of some CSS or JavaScript code, which violates the idea that this package should only transform markdown to desired HTML format.
Sorry for any ambiguity caused, but I think in the near future this is not prioritized.
